main_page:
    path: /
    controller: App\Controller\FrontController::index
video_list:
    path: /video-list
    controller: App\Controller\FrontController::videoList
video_details:
    path: /video_details
    controller: App\Controller\FrontController::videoDetails
search_results:
    path: /search_results
    controller: App\Controller\FrontController::searchResults
    methods: POST
pricing:
  path: /pricing
  controller: App\Controller\FrontController::pricing
login:
  path: /login
  controller: App\Controller\FrontController::login
register:
  path: /register
  controller: App\Controller\FrontController::register
payment:
  path: /payment
  controller: App\Controller\FrontController::payment

admin_main_page:
  path: /admin
  controller: App\Controller\AdminController::index
categories:
  path: /categories
  controller: App\Controller\AdminController::categories
edit_category:
  path: /edit-category
  controller: App\Controller\AdminController::editCategory
users:
  path: /users
  controller: App\Controller\AdminController::users
upload_video:
  path: /upload-video
  controller: App\Controller\AdminController::uploadVideo
videos:
  path: /videos
  controller: App\Controller\AdminController::videos




